# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [82]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?


############################## ANALISANDO O TEMPO DO ARRAY #####################################################
import time

# Numpy
import numpy as np

# Cria uma array unidimencional com o número 1 de elemento
one = np.array([1])
# Cria um Array para de 1000000 de 1
Array = np.repeat(one, 1000000)


# Inicia a contagem de tempo para o Array
#start_array = time.time()

#Multiplicação o Array por 2
%time for _ in range(10): Array*2

# Verifica a variação do tempo de execulção da rotina
#delta_time_array = time.time() - start_array
#print("delta_time_array = ", delta_time_array)


Wall time: 15.6 ms


In [84]:
############################## ANALISANDO O TEMPO DA LISTA #####################################################
import time

# Numpy
import numpy as np


# Criar uma lista com 1000000 de 1 como elementos
Lista = []
while len(Lista)<1000000:
    Lista.append(1)

# Inicia a contagem de tempo para a Lista
#start_lista = time.time()

#Multiplicação da Lista por 2
%time for _ in range(10): Lista2 = [x*2 for x in Lista]

# Verifica a variação do tempo de execulção da rotina
#delta_time_lista = time.time() - start_lista

#print("delta_time_lista = ", delta_time_lista)

Wall time: 610 ms


### Exercício 2

In [32]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

import numpy as np

# Criação de um array com 10 elementos

array2 = np.arange(10,100,9)
print("array2 antes = ", array2)

# Altera os valores de todos os elementos dos índices 5 a 8 para 0

i = 0
while i < len(array2):
    if (i>4)and(i<9):
        array2[i]=0
        i= i + 1
    else:
        i= i + 1

print("array2 depois= ", array2)


array2 antes =  [10 19 28 37 46 55 64 73 82 91]
array2 depois=  [10 19 28 37 46  0  0  0  0 91]


In [89]:
#Solunção 2
import numpy as np

arr = np.arange(10)
print("array antes = ", arr)

arr[5:8]=0

print("array depois = ", arr)

array antes =  [0 1 2 3 4 5 6 7 8 9]
array depois =  [0 1 2 3 4 0 0 0 8 9]


### Exercício 3

In [90]:
# Crie um array de 3 dimensões e imprima a dimensão 1
import numpy as np

# Cria um array tridimencional com elementos aleatórios
array3D = np.random.randn(3,3,3)

#Imprime todas as três dimensões
print("#Imprime todas as três dimensões\n")
print(array3D)

#Imprime a dimensão 1
print("\n\n#Imprime a dimensão 1\n")
print(array3D[0])

#Imprime todas as três dimensões

[[[ 1.91988257 -0.30365252  0.13538857]
  [ 0.2183881  -0.68878576 -0.07027844]
  [ 1.60780895 -0.51698557 -0.17055037]]

 [[-1.59367316 -2.11430628  0.4327841 ]
  [ 1.64951585 -0.95343307  0.55061245]
  [-1.64542497 -0.51867033  0.1678702 ]]

 [[-0.21654408 -0.27186256  0.1271449 ]
  [ 0.08130142 -1.12254424 -1.35140196]
  [ 1.44468241  0.22069225  0.74187819]]]


#Imprime a dimensão 1

[[ 1.91988257 -0.30365252  0.13538857]
 [ 0.2183881  -0.68878576 -0.07027844]
 [ 1.60780895 -0.51698557 -0.17055037]]


### Exercício 4

In [61]:
#1) Crie um array de duas dimensões (matriz).
#2) Imprima os elementos da terceira linha da matriz
#3) Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

import numpy as np

#1) Crio um array de duas dimensões

matriz = np.array([[3,2,1],[9,8,7],[7,5,3]])
matriz

array([[3, 2, 1],
       [9, 8, 7],
       [7, 5, 3]])

In [62]:
#2) Imprimeindo os elementos da treceira linha

print("matriz[2] = ", matriz[2])

matriz[2] =  [7 5 3]


In [92]:
#3) Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matriz[:2,1:]

array([[2, 1],
       [8, 7]])

### Exercício 5

In [2]:
# Calcule a transposta da matriz abaixo
import numpy as np

arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
help(arr.transpose)

Help on built-in function transpose:

transpose(...) method of numpy.ndarray instance
    a.transpose(*axes)
    
    Returns a view of the array with axes transposed.
    
    For a 1-D array this has no effect, as a transposed vector is simply the
    same vector. To convert a 1-D array into a 2D column vector, an additional
    dimension must be added. `np.atleast2d(a).T` achieves this, as does
    `a[:, np.newaxis]`.
    For a 2-D array, this is a standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided and
    ``a.shape = (i[0], i[1], ... i[n-2], i[n-1])``, then
    ``a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0])``.
    
    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints
    
     * None or no argument: reverses the order of the axes.
    
     * tuple of ints: `i` in the `j`-th place in the tuple means `a`'s
       `i`-th axis becomes `a.transpos

In [7]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [23]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])


# Crio uma lista de temporária
lista = []

# Inicio a varredura do array cond
i=0
for item in cond:
   if item == True:
    lista.append(xarr[i])
    i+=1
   else:
    lista.append(yarr[i])
    i+=1

# Converto a lista temporária numa matriz
Matriz = np.matrix(lista)
print(Matriz)


[[1.1 2.2 1.3 1.4 2.5]]


### Exercício 7

In [2]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

import numpy as np

# Crinando um array A de 10 elementos

A = np.array([[1,2,3,4,5],[6,7,8,9,10]])

#Você pode exportar uma matriz para um arquivo NPY usando np.save ('filename.npy', array).
np.save('MatrixA.npy',A)

#Você pode carregar uma matriz em um arquivo NPY usando np .load ('filename.npy').

B = np.copy(np.load('MatrixA.npy'))

B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Exercício 8

In [3]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

obj

0     c
1     a
2     d
3     a
4     a
5     b
6     b
7     c
8     c
9     a
10    b
dtype: object

In [5]:
# Impirmindo os valóres únicos
print(obj.unique())

['c' 'a' 'd' 'b']


### Exercício 9

In [6]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [9]:
from pandas import DataFrame
frame = DataFrame(resp)
frame

0
0     b'[{"url":"https://api.github.com/repos/pandas...
1     b'pandas","labels_url":"https://api.github.com...
2     b'hub.com/repos/pandas-dev/pandas/issues/44164...
3     b'/events","html_url":"https://github.com/pand...
4     b'4164,"title":"TST: Move some consistency rol...
...                                                 ...
1861  b" this feature request when creating `pd.Data...
1862  b' have `coerce` functionality, so the `Series...
1863  b'{"url":"https://api.github.com/repos/pandas-...
1864  b'0,"confused":0,"heart":0,"rocket":0,"eyes":0...
1865           b'ne","performed_via_github_app":null}]'

[1866 rows x 1 columns]

### Exercício 10

In [ ]:
# 1) Crie um banco de dados no SQLite,
# 2) crie uma tabela, 
# 3) insira registros, 
# 4) consulte a tabela e 
# 5) retorne os dados em dataframe do Pandas

#### 1) Criação de um banco de dados no SQLite

In [10]:
# Reemove o arquivo com o banco de dados SQLite (caso exista)
import os
os.remove("BancoTeste.db") if os.path.exists("BancoTeste.db") else None

# Importando o módulo de acesso ao SQLite
import sqlite3

# Cria uma conexão com o banco de dados. 
# Se o banco de dados não existir, ele é criado neste momento.
con = sqlite3.connect('BancoTeste.db')

# Criando um cursor 
# (Um cursor permite percorrer todos os registros em um conjunto de dados)
cur = con.cursor()

#### 2) Cria uma tabela

In [11]:
# Cria uma instrução sql
sql_create = 'create table cursos '\
'(id integer primary key, '\
'titulo varchar(100), '\
'categoria varchar(140))'

# Executando a instrução sql no cursor
cur.execute(sql_create)

#### 3) Inserindo registros

In [12]:
# Criando outra sentença SQL para inserir registros
sql_insert = 'insert into cursos values (?, ?, ?)'

# Dados
recset = [(1000, 'Ciência de Dados', 'Data Science'),
          (1001, 'Big Data Fundamentos', 'Big Data'),
          (1002, 'Python Fundamentos', 'Análise de Dados')]

# Inserindo os registros
for rec in recset:
    cur.execute(sql_insert, rec)
    
# Grava a transação
con.commit()

#### 4) Consultando a tabela

In [14]:
# Criando outra sentença SQL para selecionar registros
sql_select = 'select * from cursos'

# Seleciona todos os registros e recupera os registros
cur.execute(sql_select)
dados = cur.fetchall()

#### 5) Retorna os dados em dataframe do Pandas

In [15]:
# Chamo o DataFrame no Pandas
from pandas import DataFrame
frame = DataFrame(dados)
frame

0                     1                 2
0  1000      Ciência de Dados      Data Science
1  1001  Big Data Fundamentos          Big Data
2  1002    Python Fundamentos  Análise de Dados

In [18]:
# Formatando o nome das colunas
DataFrame(dados, columns = ['ID', 'Título', 'Categoria'])

ID                Título         Categoria
0  1000      Ciência de Dados      Data Science
1  1001  Big Data Fundamentos          Big Data
2  1002    Python Fundamentos  Análise de Dados

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
